[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rt = {path ="../rt"}
log = {path ="../log"}
cortex-m-semihosting  = "0.5.0"
cortex-m = "0.7.6"
